// <auto-generated />
namespace PassionProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removerecipetype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removerecipetype));
        
        string IMigrationMetadata.Id
        {
            get { return "202106250100524_remove-recipetype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
